application: cmdlinenotify
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_ah/spi/.*
  script: jobapi.application
  secure: optional

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?index\.yaml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?client\.py$
