application: cmdlinenotify
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /javascript
  static_dir: javascript
  secure: always

- url: /.*
  script: notify.application
  secure: always